{"name": "Check for Duplicate Users", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[contains(text(),'User already exists with username or email')]\"}\n  (Session info: chrome=131.0.6778.205); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF70A37FB05+28789]\n\t(No symbol) [0x00007FF70A2E86E0]\n\t(No symbol) [0x00007FF70A18592A]\n\t(No symbol) [0x00007FF70A1D930E]\n\t(No symbol) [0x00007FF70A1D95FC]\n\t(No symbol) [0x00007FF70A2228A7]\n\t(No symbol) [0x00007FF70A1FF47F]\n\t(No symbol) [0x00007FF70A21F654]\n\t(No symbol) [0x00007FF70A1FF1E3]\n\t(No symbol) [0x00007FF70A1CA938]\n\t(No symbol) [0x00007FF70A1CBAA1]\n\tGetHandleVerifier [0x00007FF70A6B933D+3410093]\n\tGetHandleVerifier [0x00007FF70A6CE7DD+3497293]\n\tGetHandleVerifier [0x00007FF70A6C2A73+3448803]\n\tGetHandleVerifier [0x00007FF70A447BBB+848171]\n\t(No symbol) [0x00007FF70A2F3C3F]\n\t(No symbol) [0x00007FF70A2EF6E4]\n\t(No symbol) [0x00007FF70A2EF87D]\n\t(No symbol) [0x00007FF70A2DED49]\n\tBaseThreadInitThunk [0x00007FF9B25FE8D7+23]\n\tRtlUserThreadStart [0x00007FF9B34DFBCC+44]\n\n", "trace": "  File \"C:\\Users\\syedt\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\syedt\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"steps\\PlatformAdminCreation_Steps.py\", line 204, in step_impl\n    error_message8 = context.driver.find_element(By.XPATH, \"//div[contains(text(),'User already exists with username or email')]\")\n  File \"C:\\Users\\syedt\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 770, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\syedt\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\syedt\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given I log in to the TNA application as an admin and click on the \"Create New User\" button", "status": "passed", "start": 1735901485479, "stop": 1735901492280}, {"name": "When I input the details of an already existing platform admin and click on the save button", "status": "passed", "start": 1735901492280, "stop": 1735901492769}, {"name": "Then I should see an error message stating \"User already exists\"", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[contains(text(),'User already exists with username or email')]\"}\n  (Session info: chrome=131.0.6778.205); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF70A37FB05+28789]\n\t(No symbol) [0x00007FF70A2E86E0]\n\t(No symbol) [0x00007FF70A18592A]\n\t(No symbol) [0x00007FF70A1D930E]\n\t(No symbol) [0x00007FF70A1D95FC]\n\t(No symbol) [0x00007FF70A2228A7]\n\t(No symbol) [0x00007FF70A1FF47F]\n\t(No symbol) [0x00007FF70A21F654]\n\t(No symbol) [0x00007FF70A1FF1E3]\n\t(No symbol) [0x00007FF70A1CA938]\n\t(No symbol) [0x00007FF70A1CBAA1]\n\tGetHandleVerifier [0x00007FF70A6B933D+3410093]\n\tGetHandleVerifier [0x00007FF70A6CE7DD+3497293]\n\tGetHandleVerifier [0x00007FF70A6C2A73+3448803]\n\tGetHandleVerifier [0x00007FF70A447BBB+848171]\n\t(No symbol) [0x00007FF70A2F3C3F]\n\t(No symbol) [0x00007FF70A2EF6E4]\n\t(No symbol) [0x00007FF70A2EF87D]\n\t(No symbol) [0x00007FF70A2DED49]\n\tBaseThreadInitThunk [0x00007FF9B25FE8D7+23]\n\tRtlUserThreadStart [0x00007FF9B34DFBCC+44]\n\n", "trace": "  File \"C:\\Users\\syedt\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\syedt\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"steps\\PlatformAdminCreation_Steps.py\", line 204, in step_impl\n    error_message8 = context.driver.find_element(By.XPATH, \"//div[contains(text(),'User already exists with username or email')]\")\n  File \"C:\\Users\\syedt\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 770, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\syedt\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\syedt\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1735901492769, "stop": 1735901494804}], "attachments": [{"name": "Check for Duplicate Users (Fail)", "source": "5e0a84a3-eeac-4bfb-a576-44fd238eb5a9-attachment.png", "type": "image/png"}], "start": 1735901485478, "stop": 1735901497156, "uuid": "f49ccdca-757c-4a0e-89da-bf6552a8e425", "historyId": "6a4a98b2d226d1d6bca4de216f467e7a", "fullName": "Platform Admin Management: Check for Duplicate Users", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "Negative"}, {"name": "tag", "value": "order_2"}, {"name": "feature", "value": "Platform Admin Management"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}